package com.example.springstatemachine.domain;

public enum CheckoutEvent {
   VERIFYING_CARD, DECLINED_CARD, APPROVED_CARD, FUNDS_SUFFICIENT, FUNDS_INSUFFICIENT, APPROVING_PAYMENT, CANCELLING_PAYMENT
}
